services:
  gvm-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - MAILJET_PUBLIC_KEY=${MAILJET_PUBLIC_KEY}
      - MAILJET_SECRET_KEY=${MAILJET_SECRET_KEY}
      - ENVIRONMENT=${ENVIRONMENT}
      - PORT=${PORT}
    env_file:
      - .env
